services:
  - type: web
    name: shadow-stars-bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    healthCheckPath: ""
    envVars:
      - key: BOT_TOKEN
        value: 8257333913:AAFe1GLABCtuA3zVFKq_hTI_G3Dw8VGtJJ0
      - key: ADMIN_CHAT_ID
        value: 1003594449373
      - key: PORT
        value: 8080
